export { default as AdultsSvg } from '@/assets/svg/icon-adults.svg';
export { default as AllSvg } from '@/assets/svg/icon-all.svg';
export { default as BanSvg } from '@/assets/svg/icon-ban.svg';
export { default as Ban2Svg } from '@/assets/svg/icon-ban-2.svg';
export { default as CaretDown } from '@/assets/svg/icon-caret-down.svg';
export { default as CaretUp } from '@/assets/svg/icon-caret-up.svg';
export { default as CheckSvg } from '@/assets/svg/icon-check.svg';
export { default as CheckCircleSvg } from '@/assets/svg/icon-check-circle.svg';
export { default as CloseSvg } from '@/assets/svg/icon-close.svg';
export { default as DentistSvg } from '@/assets/svg/icon-dentist.svg';
export { default as DotsVertSvg } from '@/assets/svg/icon-dots-vertical.svg';
export { default as FamilyDrSvg } from '@/assets/svg/icon-family-dr.svg';
export { default as FbSvg } from '@/assets/svg/icon-fb.svg';
export { default as FilterSvg } from '@/assets/svg/icon-filter.svg';
export { default as GynSvg } from '@/assets/svg/icon-gynecologist.svg';
export { default as ClinicSvg } from '@/assets/svg/icon-clinic.svg';
export { default as PedSvg } from '@/assets/svg/icon-kids.svg';
export { default as LinkSvg } from '@/assets/svg/icon-link.svg';
export { default as ListSvg } from '@/assets/svg/icon-list-view.svg';
export { default as MapSvg } from '@/assets/svg/icon-map-view.svg';
export { default as PhoneNoneSvg } from '@/assets/svg/icon-phone-none.svg';
export { default as PhoneSvg } from '@/assets/svg/icon-phone.svg';
export { default as SearchSvg } from '@/assets/svg/icon-search.svg';
export { default as StudentsSvg } from '@/assets/svg/icon-students.svg';
export { default as TwSvg } from '@/assets/svg/icon-tw.svg';
export { default as LogoSvg } from '@/assets/svg/zdravniki-sledilnik-logo.svg';

export { icons } from './icons';

export { default as Icon } from './Icon';
export type { IconName, IconProps } from './Icon';
